### PR TITLE
feat: enable bitbucket cloud scm provider (v2)

### PR DESCRIPTION
**Pull request by mmerrill3**
Implementation for #459

### CODE REVIEW

**Comment by mmerrill3** [comment]
@crenshaw-dev ready for review.

**Comment by wtam2018** [comment]
LGTM

**Comment by rishabh625** [comment]
LGTM as well

**Review by wtam2018 — APPROVED** [review]

**Comment by rishabh625** [comment]
appologies for delay as [merge](https://github.com/argoproj/argo-cd/pull/8864) was being considered

**Comment by mmerrill3** [comment]
@rishabh625 glad to contribute.  Thanks for merging.

**Pull request merged**
