### PR TITLE
chore: add arm64 image to build (#478)

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes https://github.com/argoproj/applicationset/issues/478

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by wtam2018** [comment]
LGTM 
Thanks @crenshaw-dev !

**Comment by wernerb** [comment]
`0.4.0` does not seem to have an arm64 build: https://quay.io/repository/argoproj/argocd-applicationset?tab=tags&tag=latest (neither does latest)

**Comment by d3v2null** [comment]
Confirming `0.4.1` also doesn't have an arm64 build -
ArgoCD 2.3.X doesn't fully support arm architecture then, since applicationset is now bundled in

Manifest
```{
    "Name": "quay.io/argoproj/argocd-applicationset",
    "Digest": "sha256:7433ff9dc5f4fccf13f71be514982740f32cd31707734ce8934f149d26163590",
    "RepoTags": [
        "v0.1.0",
        "v0.2.0",
        "v0.3.0",
        "latest",
        "v0.4.0",
        "v0.4.1"
    ],
    "Created": "2022-03-10T13:53:33.310145635Z",
    "DockerVersion": "20.10.12",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:24496884391b0c292a71ad3f46bb689ff34f0dee4454901252ba7d52a977bbb0",
        "sha256:4f42d2d5e1f6322e9dffb4a18f539e6d5dec6b36f66f10c4d4bce0dff3ec3c26",
        "sha256:1c3842caf26c905b022ea2300cdd60bc85116423a4eb14345994c62d02d7c60f",
        "sha256:85f7cff480492b56a2da01acaf5804b5726201440e7c612770419e101ca3874a",
        "sha256:589e091e1b0884339672c761874d3936f498672823658650612d006338f333c6",
        "sha256:860fc5c078f037f1121382b94ae4c31a01358976e0f037ada359832ecb49c77e",
        "sha256:4524a3f3b4fa275afba586b815081c242d415996be6a8f806c22f007518459ce",
        "sha256:d309de07404e1ec9c08ade4df5ab79c1b9e8c22575356b4aa7cd3b598e163931",
        "sha256:892445a15b42f5c076f76790fb574cc7bec152ca8efa37c2658037565150f613",
        "sha256:85c97bb3d0550d20d5812312eda67ad71eec3c848c57740128dda979bea6898e"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "DEBIAN_FRONTEND=noninteractive"
    ]
}

**Comment by dirien** [comment]
Can confirm this too, while adding ArgoCD to microk8s via the Helm chart.

https://github.com/canonical/microk8s-community-addons/pull/35

**Pull request merged**
