### PR TITLE
Add labelSelector style to filter all generators

### LINKED ISSUE #361: Allow to filter each generator by a selector like a labelSelector
We are currently use applicationset to deploy multiple applications into a same set of clusters, but some application are just need in certain clusters. It would be greated to use a selector to post filter any generator output.

Idea:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
        - cluster: engineering-dev
          url: https://kubernetes.default.svc
          env: staging
        - cluster: engineering-prod
          url: https://kubernetes.default.svc
          env: prod
    selector:
      matchLabels:
        env: staging
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```

### PR DESCRIPTION
**Pull request by farodin91**
Fixes #361

### CODE REVIEW

**Comment by wtam2018** [comment]
We need to update the documentation.

**Comment by farodin91** [comment]
@wtam2018 I would like to move the condition into generators to make it more convenient. I will around with different ideas.

**Comment by farodin91** [comment]
@wtam2018 I changed the behavior to be more consistent.

**Comment by daskanu** [comment]
Any updates on this? 
We really like this feature and would appreciate it to become a part of an official release as soon as possible.

**Comment by farodin91** [comment]
@wtam2018 Would you like to review? I fixed all build failures and updated the documentation.

**Comment by farodin91** [comment]
@alexmt would someone like to review my PR?

**Comment by rishabh625** [comment]
@jgwest : does this PR have a valid usecase?

**Comment by philipp1992** [comment]
HI,
we are already using this feature and would like to see this in the release.
kind regards
Philipp

**Comment by rishabh625** [comment]
@farodin91 :  Can u please move this PR into argocd as applicationset is [moved](https://github.com/argoproj/argo-cd/pull/8864). If u find it laborious, i can do it on your behalf with your consent

**Comment by farodin91** [comment]
Closed by https://github.com/argoproj/argo-cd/pull/8980

**Pull request closed without merging**
